Prepared By [Izam Mohammed](https://github.com/izam-mohammed) 😊. Follow for more ❤️.

#### Basic Libraries

In [8]:
# basic libraries

import sklearn
import pandas as np
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, precision_score, recall_score, roc_auc_score

%matplotlib inline

## Logistic Regression

#### with sklearn

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris # a sample data

In [10]:
# loading the data
iris = load_iris()
X = iris.data
y = iris.target

X.shape, y.shape

((150, 4), (150,))

In [11]:
# data for binary classification
y_binary = (y==0).astype(int)

y_binary.shape

(150,)

In [12]:
# splitting
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.2, random_state=42)

X_train[:5]

array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2]])

In [13]:
# initialise the model
model = LogisticRegression(
    penalty='l2',
    C=1.0,
    solver='liblinear',
    max_iter = 100,
    random_state=42,
)

In [14]:
# fit to the model
model.fit(X_train, y_train)

LogisticRegression(random_state=42, solver='liblinear')

In [15]:
# making predictions
y_pred = model.predict(X_test)

In [16]:
# Calculate accuracy and other performance metrics
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)
f1_score = f1_score(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy}")
print(f"precision: {precision}")
print(f"Recall: {recall}")
print(f"ROC AUC: {roc_auc}")
print(f"f1 score: {f1_score}")
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Accuracy: 1.0
precision: 1.0
Recall: 1.0
ROC AUC: 1.0
f1 score: 1.0

Confusion Matrix:
 [[20  0]
 [ 0 10]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [17]:
# some attributes of model

coef = model.coef_
intercept = model.intercept_
classes = model.classes_
iterations = model.n_iter_
n_features = model.n_features_in_

# printing all

print(f"Coefficient - {coef}")
print(f"Intercept - {intercept}")
print(f"classes - {classes}")
print(f"iterations - {iterations}")
print(f"number of features - {n_features}")

Coefficient - [[ 0.3711229   1.409712   -2.15210117 -0.95474179]]
Intercept - [0.2478905]
classes - [0 1]
iterations - [7]
number of features - 4


#### from scratch

In [18]:
# loading the data
iris = load_iris()
X = iris.data
y = iris.target

# data for binary classification
y_binary = (y==0).astype(int)

# splitting
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.2, random_state=42)

In [19]:
# setting constraints

learning_rate = 0.01
num_iteration = 1000
weights = np.zeros(X_train.shape[1])
bias = 0
m = len(y_train)

In [20]:
# sigmoid function
def sigmoid(z):
  return 1/ (1 + np.exp(-z))

In [21]:
# optimizing (Gradient descent)

for _ in range(num_iteration):
  linear_model = np.dot(X_train, weights) + bias
  y_pred = sigmoid(linear_model)

  gradient_w = np.dot(X_train.T, (y_pred - y_train))
  gradient_b = np.sum(y_pred - y_train) / m

  weights -= learning_rate * gradient_w
  bias -= learning_rate * gradient_b

In [22]:
# weights and bias

print(f"weights - {weights}")
print(f"biases - {bias}")

weights - [ 0.88526053  2.95627821 -4.5120135  -2.06605549]
biases - 0.004565160257030802


In [23]:
# predict function

def predict(x):
  linear_model = np.dot(x, weights)+ bias
  y_pred = sigmoid(linear_model)
  y_pred_class = (y_pred >= 0.5).astype(int)
  return y_pred_class

y_pred = predict(X_test)

In [24]:
# accuracy

print(f"Accuracy - {accuracy_score(y_test, y_pred)}")

Accuracy - 1.0


## KNN

#### with sklearn

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
# load data
iris = load_iris()
X = iris.data
y = iris.target

In [27]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
# initialize
model = KNeighborsClassifier(
    n_neighbors=3,
    weights='uniform',
    algorithm='auto',
    metric='euclidean',
    n_jobs=-1
)

In [29]:
# trainging
model.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_jobs=-1, n_neighbors=3)

In [30]:
# Make predictions on the test data
y_pred = model.predict(X_test)

In [31]:
# Calculate accuracy and other performance metrics
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy}")
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [32]:
# Access and print model attributes
n_neighbors = model.n_neighbors
effective_metric_ = model.effective_metric_
classes_ = model.classes_
outputs_2d_ = model.outputs_2d_
n_features = model.n_features_in_
n_samples = model.n_samples_fit_

print(f"Number of Neighbors: {n_neighbors}")
print(f"Effective Metric: {effective_metric_}")
print(f"Classes: {classes_}")
print(f"Outputs 2D: {outputs_2d_}")
print(f"Number of features - {n_features}")
print(f"Number of samples - {n_samples}")

Number of Neighbors: 3
Effective Metric: euclidean
Classes: [0 1 2]
Outputs 2D: False
Number of features - 4
Number of samples - 120


#### from scratch

In [33]:
# load data
iris = load_iris()
X = iris.data
y = iris.target

In [34]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

There is no fitting at all (No need for optimization). So we can write the entire thing as per OOP concepts

In [35]:
# KNN

class KNN:
  def __init__(self, k=3):
    self.k = k

  def fit(self, X, y):
    self.X_train = X
    self.y_train = y

  # we are using euclidean distance to find the distance
  def euclidian(self, a, b):
    return np.sqrt(np.sum((a - b) ** 2))

  def predict(self, X):
    y_pred = [self._predict(x) for x in X]
    return np.array(y_pred)

  # Individul value prediction
  def _predict(self, x):
    # finding the distance between every point
    distances = [self.euclidian(x, x_train) for x_train in self.X_train]

    # find the index of closest k values
    k_indices = np.argsort(distances)[:self.k]

    # finding the values in y_train
    k_nearest_labels = [self.y_train[i] for i in k_indices]

    # perform a voting and finding most common
    most_common = np.bincount(k_nearest_labels).argmax()
    return most_common

In [36]:
# model initiating
model = KNN()
model.fit(X, y)

In [37]:
# predict
y_pred = model.predict(X_test)

In [38]:
accuracy = np.mean(y_pred == y_test)
print(f"Accuracy - {accuracy}")

Accuracy - 1.0


## Multinomial Naive Bayes

Used for Discreate data

#### With sklearn

In [39]:
# importing

from sklearn.datasets import fetch_20newsgroups
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
# load the data
newsgroups = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))
X = newsgroups.data
y = newsgroups.target

len(X), len(y)

(18846, 18846)

In [41]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
# Create a CountVectorizer to convert text data into numerical features
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [43]:
model = MultinomialNB()
model.fit(X_train_vec, y_train)

MultinomialNB()

In [44]:
# predicting
y_pred = model.predict(X_test_vec)

In [45]:
# Calculate accuracy and other performance metrics
accuracy = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred, target_names=newsgroups.target_names)

# Print the results
print(f"Accuracy: {accuracy}")
print("\nClassification Report:\n", class_report)

Accuracy: 0.6175066312997347

Classification Report:
                           precision    recall  f1-score   support

             alt.atheism       0.61      0.25      0.36       151
           comp.graphics       0.48      0.75      0.58       202
 comp.os.ms-windows.misc       0.73      0.04      0.08       195
comp.sys.ibm.pc.hardware       0.53      0.73      0.62       183
   comp.sys.mac.hardware       0.86      0.58      0.69       205
          comp.windows.x       0.68      0.80      0.74       215
            misc.forsale       0.88      0.53      0.66       193
               rec.autos       0.87      0.63      0.73       196
         rec.motorcycles       0.49      0.58      0.53       168
      rec.sport.baseball       0.99      0.67      0.80       211
        rec.sport.hockey       0.92      0.80      0.86       198
               sci.crypt       0.59      0.77      0.67       201
         sci.electronics       0.84      0.49      0.62       202
                 sci.

In [46]:
# attributes

alpha = model.alpha  # Smoothing parameter (default is 1.0)
class_count = model.class_count_  # Number of samples encountered for each class
class_log_prior = model.class_log_prior_  # Log probability of each class (prior)
feature_count = model.feature_count_  # Number of samples for each (class, feature) pair
feature_log_prob = model.feature_log_prob_  # Log probability of each feature given a class
n_classes = model.classes_  # List of unique class labels
n_features = model.n_features_in_  # Number of features (determined during fitting)

print(f"Smoothing Parameter (alpha): {alpha}")
print(f"Number of Samples per Class: {class_count[:4]}")
print(f"Log Prior Probabilities for Classes: {class_log_prior[:4]}")
print(f"Number of Samples per (Class, Feature) Pair: {feature_count[:4]}")
print(f"Log Probabilities of Features Given Class: {feature_log_prob[:4]}")
print(f"Unique Class Labels: {n_classes}")
print(f"Number of Features: {n_features}")

Smoothing Parameter (alpha): 1.0
Number of Samples per Class: [648. 771. 790. 799.]
Log Prior Probabilities for Classes: [-3.14696866 -2.97317098 -2.94882641 -2.93749841]
Number of Samples per (Class, Feature) Pair: [[ 0. 15.  0. ...  0.  0.  0.]
 [59. 14.  1. ...  0.  0.  0.]
 [35.  3.  0. ...  0.  0.  0.]
 [51. 12.  0. ...  0.  0.  0.]]
Log Probabilities of Features Given Class: [[-12.35491498  -9.58232625 -12.35491498 ... -12.35491498 -12.35491498
  -12.35491498]
 [ -8.38363894  -9.7699333  -11.78483632 ... -12.4779835  -12.4779835
  -12.4779835 ]
 [ -9.05465101 -11.25187559 -12.63816995 ... -12.63816995 -12.63816995
  -12.63816995]
 [ -8.28445083  -9.6707452  -12.23569455 ... -12.23569455 -12.23569455
  -12.23569455]]
Unique Class Labels: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Number of Features: 111584


#### form scratch

In [47]:
class MultinomialNaiveBayes:
  def __init__(self, alph=1.0):
    self.alpha = alpha # laplace smoothing parameter
    self.class_counts = {}
    self.feature_counts = {}
    self.class_probs = {}

  def fit(self, X, y):
    n_samples, n_features = X.shape
    self.classes = np.unique(y)
    n_classes = len(self.classes)

    for c in self.classes:
      X_c = X[y==c]
      self.class_counts[c] = X_c.shape[0]
      self.feature_counts[c] = X_c.sum(axis=0)

      # laplance smoothing
      self.feature_counts[c] = (self.feature_counts[c] + self.alpha) / self.class_counts[c] + self.alpha * n_features

      # caluculate class probability
      self.class_probs[c] = self.class_counts[c] / n_samples

  def predict(self, X):
    y_pred = [self._predict(x) for x in X]
    return y_pred

  def _predict(self, x):
    posteriors = {}
    for c in self.classes:
      prior = np.log(self.class_probs[c])
      likelihood = np.log(self.feature_counts[c][x>0]).sum()
      posteriors[c] = prior + likelihood

    return max(posteriors, key=posteriors.get)

In [48]:
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

model = MultinomialNaiveBayes()
model.fit(X, y)

X.shape, y.shape

((6, 100), (6,))

## Gausian Naive Bayes

Used for Continuous data

#### with sklearn

In [49]:
# importing
from sklearn.naive_bayes import GaussianNB

In [50]:
# data
X = np.array([[-1, -1],
              [-2, -1],
              [-3, -2],
              [1, 1],
              [2, 1],
              [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])

In [51]:
# model
model = GaussianNB()

In [52]:
# fitting

model.fit(X, Y)

GaussianNB()

In [53]:
# predicting
print(model.predict([[-0.8, -1]]))

[1]


#### from scratch

In [71]:
import numpy as np

class GaussianNaiveBayes:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.parameters = []

        for i, c in enumerate(self.classes):
            X_c = X[y == c]
            self.parameters.append([])
            for feature in X_c.T:
                mean, std = np.mean(feature), np.std(feature)
                self.parameters[i].append((mean, std))

    def _pdf(self, x, mean, std):
        exponent = np.exp(-((x - mean) ** 2 / (2 * std ** 2)))
        return (1 / (np.sqrt(2 * np.pi) * std)) * exponent

    def _predict_class(self, x):
        posteriors = []

        for i, c in enumerate(self.classes):
            prior = np.log(len(X[y == c]) / len(X))
            posterior = prior + np.sum(np.log(self._pdf(x, *params)) for params in self.parameters[i])
            posteriors.append(posterior)

        return self.classes[np.argmax(posteriors)]

    def predict(self, X):
        y_pred = [self._predict_class(x) for x in X]
        return y_pred

In [72]:
# Generate some example data
X = np.array([[1, 1], [2, 2], [3, 3], [6, 6], [7, 7], [8, 8]])
y = np.array([0, 0, 0, 1, 1, 1])

In [73]:
# Create and fit the Gaussian Naive Bayes model
model = GaussianNaiveBayes()
model.fit(X, y)

In [79]:
# Make predictions
new_data = np.array([[4, 4]])
predictions = model.predict(new_data)

print("Predictions:", predictions)

Predictions: [0]


<ipython-input-71-76d0ed421119>:24: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  posterior = prior + np.sum(np.log(self._pdf(x, *params)) for params in self.parameters[i])


'h'