## Tensors

In [1]:
# getting the libaray

import torch

### checking the cuda

In [10]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

### basic setup

In [9]:
my_tensor = torch.tensor(
    [[1,2,3],[6,7,8]],
    dtype=torch.float32,
    device = "cpu",
    requires_grad = True,   # for auto grad
    )
my_tensor

tensor([[1., 2., 3.],
        [6., 7., 8.]], requires_grad=True)

### some attributes of tensor

In [18]:
print("dtype -> ", my_tensor.dtype)
print("device -> ", my_tensor.device)
print("shape -> ", my_tensor.shape)
print("require_grad -> ", my_tensor.requires_grad)

dtype ->  torch.float32
device ->  cpu
shape ->  torch.Size([2, 3])
require_grad ->  True


### common initializers

In [19]:
x = torch.empty(size = (3,3))
x

tensor([[-1.5013e-22,  3.3121e-41, -1.4840e-22],
        [ 3.3121e-41,  8.9683e-44,  0.0000e+00],
        [ 1.3452e-43,  0.0000e+00, -3.2272e+03]])

In [20]:
x = torch.zeros((4,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
x = torch.rand((3,3))
x

tensor([[0.8271, 0.1034, 0.3770],
        [0.5630, 0.0605, 0.9023],
        [0.7128, 0.0931, 0.0730]])

In [22]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
x = torch.eye(3,3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [25]:
x = torch.arange(0, 6, 1)
x

tensor([0, 1, 2, 3, 4, 5])

In [28]:
x = torch.linspace(1, 2, 5)
x

tensor([1.0000, 1.2500, 1.5000, 1.7500, 2.0000])

In [29]:
x = torch.empty(size = (1,5)).normal_(mean=0, std=1)
x

tensor([[ 0.7655,  0.7898, -1.8572, -1.9501, -0.5045]])

In [31]:
x = torch.empty(size = (1,6)).uniform_(0,1)
x

tensor([[0.4086, 0.7760, 0.1109, 0.4925, 0.0202, 0.9974]])

In [32]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### initialize and convert to other types

In [33]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [34]:
tensor.bool()

tensor([False,  True,  True,  True])

In [35]:
tensor.short()   # ot int 16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [39]:
print(tensor.long().dtype)
tensor.long()                # to int 64 (imp)

torch.int64


tensor([0, 1, 2, 3])

In [40]:
tensor.half()    # to float 16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [42]:
print(tensor.float().dtype)
tensor.float()   # float 32 (imp)

torch.float32


tensor([0., 1., 2., 3.])

In [43]:
tensor.double()     # float 64

tensor([0., 1., 2., 3.], dtype=torch.float64)

### to arrays and vise versa

In [45]:
import numpy as np
arr = np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
tensor = torch.from_numpy(arr)
tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [48]:
np_arr = tensor.numpy()
np_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Tensor math

In [49]:
x = torch.tensor([1,3,4])
y = torch.tensor([6,7,8])

In [50]:
# addition

z1 = torch.empty(3)
torch.add(x, y, out=z1)
z1

tensor([ 7., 10., 12.])

In [51]:
z2 = torch.add(x, y)
z2

tensor([ 7, 10, 12])

In [53]:
z3 = x + y
z3

tensor([ 7, 10, 12])

In [54]:
# substraction

z = x - y
z

tensor([-5, -4, -4])

In [55]:
# division

z = torch.true_divide(x, y)
z

tensor([0.1667, 0.4286, 0.5000])

In [56]:
# inplace operations

t = torch.zeros(3)
t.add_(x)         # t is modified
t

tensor([1., 3., 4.])

In [57]:
t += x  # other way
t

tensor([2., 6., 8.])

In [58]:
# exponent

z = x.pow(2)
z

tensor([ 1,  9, 16])

In [61]:
x ** 2    # other way

tensor([ 1,  9, 16])

In [62]:
# simple comparison
x < 0

tensor([False, False, False])

In [63]:
x > 3

tensor([False, False,  True])

In [64]:
# matrix multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

y = torch.mm(x1, x2)
y

tensor([[1.3110, 1.0349, 1.1331],
        [1.8696, 1.7395, 1.6690]])

In [65]:
y2 = x1.mm(x2)
y2

tensor([[1.3110, 1.0349, 1.1331],
        [1.8696, 1.7395, 1.6690]])

In [67]:
# matrix exponentiation

matrix_exp = torch.rand(5, 5)
matrix_exp.matrix_power(3)

tensor([[2.2482, 2.7353, 2.2790, 3.0151, 2.0783],
        [3.2558, 4.3509, 3.5349, 4.2765, 3.1444],
        [3.3657, 4.6448, 3.7318, 4.3453, 3.5226],
        [3.2739, 4.5802, 3.7451, 4.6578, 3.3612],
        [3.4650, 4.5749, 3.7556, 4.7388, 3.5090]])

In [70]:
# element wise multiplication

x = torch.tensor([1,3,4])
y = torch.tensor([6,7,8])

z = x * y
z

tensor([ 6, 21, 32])

In [71]:
# dot product

z = torch.dot(x, y)
z

tensor(59)

In [73]:
# batch multiplication

batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

output_bmm = torch.bmm(tensor1, tensor2)   # the output shape will be (batch, n, p)
output_bmm.shape

torch.Size([32, 10, 30])

### Broadcasting

In [79]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))
print(x1, x2, sep="\n", end="\n\n\n")

z = x1 - x2
z                   #  the second vector is broadcasted to higher dimention
                    #  just like in numpy

tensor([[0.4705, 0.4615, 0.7951, 0.8788, 0.7667],
        [0.1243, 0.9109, 0.9115, 0.6084, 0.8990],
        [0.0644, 0.2327, 0.1516, 0.2218, 0.9682],
        [0.7477, 0.9802, 0.3599, 0.7488, 0.4414],
        [0.4176, 0.2380, 0.8865, 0.0712, 0.3608]])
tensor([[0.7535, 0.0412, 0.8762, 0.5182, 0.6760]])




tensor([[-0.2831,  0.4203, -0.0811,  0.3606,  0.0907],
        [-0.6293,  0.8697,  0.0353,  0.0902,  0.2230],
        [-0.6892,  0.1915, -0.7246, -0.2964,  0.2922],
        [-0.0059,  0.9390, -0.5163,  0.2306, -0.2346],
        [-0.3360,  0.1968,  0.0103, -0.4470, -0.3153]])

### some other useful operations

In [81]:
sum_x = torch.sum(x, dim=0)
sum_x

tensor(8)

In [83]:
values, indices = torch.max(x, dim=0)
values, indices

(tensor(4), tensor(2))

In [84]:
values, indices = torch.min(x, dim=0)
values, indices

(tensor(1), tensor(0))

In [85]:
abs_x = torch.abs(x)
abs_x

tensor([1, 3, 4])

In [87]:
a_max = torch.argmax(x, dim=0)
a_max

tensor(2)

In [89]:
mean_x = torch.mean(x.float(), dim=0)
mean_x

tensor(2.6667)

In [91]:
y # checking the y

tensor([6, 7, 8])

In [93]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)
sorted_y, indices

(tensor([6, 7, 8]), tensor([0, 1, 2]))

In [94]:
z = torch.clamp(x, min=0, max=2)  # in a range
z

tensor([1, 2, 2])

In [99]:
x = torch.tensor([1,2,43,40,0], dtype=torch.bool)
z = torch.any(x)
z

tensor(True)

In [100]:
z = torch.all(x)
z

tensor(False)

In [122]:
x = torch.tensor([1,1,1,2,3,4,4,4,4,3])
x.unique()

tensor([1, 2, 3, 4])

In [127]:
x.ndimension()

1

In [129]:
x.numel()  # length

10

In [130]:
torch.where(x>5, x, x*2)

tensor([2, 2, 2, 4, 6, 8, 8, 8, 8, 6])

### Indexing

In [103]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
x[0].shape

torch.Size([25])

In [104]:
x[:, 0].shape

torch.Size([10])

In [105]:
x[2, 0:10]

tensor([0.9446, 0.5631, 0.9246, 0.6101, 0.6768, 0.8756, 0.9751, 0.4759, 0.4441,
        0.7318])

In [108]:
# we can assign like that also

x[0,0] = 100
x[0][0]

tensor(100.)

In [109]:
# a bit fancy indexing

x = torch.arange(10)
indices = [2,5,8]
x[indices]

tensor([2, 5, 8])

In [113]:
# in a 2d manner

x = torch.rand((3,4))
rows = torch.tensor([1,0])
cols = torch.tensor([2,3])
x[rows, cols].shape

torch.Size([2])

In [115]:
# A bit advanced indexing

x  = torch.arange(10)
x[(x<2) | (x>8)]

tensor([0, 1, 9])

In [118]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

### with shapes

In [133]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])